# Generated by Django 4.2.10 on 2024-03-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="callback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("mobile_no", models.CharField(blank=True, max_length=10, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("paragraph", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
