# Generated by Django 4.2.10 on 2024-03-02 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="callback",
        ),
    ]
